# Generated by Django 5.2.12 on 2026-03-03 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='current_period_start',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_period_start',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
