# Generated by Django 5.2.12 on 2026-03-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('exaggeration_score', models.FloatField(default=0.0)),
                ('credibility_score', models.FloatField(default=0.0)),
                ('emotional_intensity', models.FloatField(default=0.0)),
                ('final_risk_score', models.FloatField(default=0.0)),
                ('ml_probability', models.FloatField(default=0.0)),
                ('feature_snapshot', models.JSONField(default=dict)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('recommendations', models.JSONField(default=list)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.textsubmission')),
            ],
        ),
    ]
