# Generated by Django 5.2.12 on 2026-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsubmission',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='textsubmission',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
