# Generated by Django 5.2.12 on 2026-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_textsubmission_document_alter_textsubmission_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='annotation_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='contribution_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
