# Generated by Django 5.2.12 on 2026-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisresult_annotation_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='rewrite_changes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='rewrite_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='rewritten_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
